apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-cluster
  region: us-west-2
  version: "1.21"
vpc:
  id: vpc-0ce06add84b6edea1
  securityGroup: "sg-0fca48ed53baaa4f9"
  subnets:
    public:
      us-west-2a: { id: subnet-0833d4398e6592d0a }
      us-west-2b: { id: subnet-003dfeebe7b41e56f }
      us-west-2c: { id: subnet-0abeab68b041bdf52 }
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  serviceRoleARN: "arn:aws:iam::531829985530:role/EksClusterRole"
managedNodeGroups:
  - name: dev-nodes
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    instanceType: t3.medium
    iam:
      instanceRoleARN: arn:aws:iam::531829985530:role/EksNodeRole
